#!/usr/bin/env sh

export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=wlr

#sway window swallowing
alias mpv='swayhide mpv'
exec /usr/bin/sway "$@"

#Only uncomment the lines below if you're starting dwl without a display manager. 
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_WAYLAND_DISABLE_WINDOWEDECORATION=1
export GTK_THEME="Breeze-Dark"
export XCURSOR_THEME="Breeze-Dark"
export XCURSOR_SIZE=24
export GRIM_DEFAULT_DIR="$HOME/pictures/screenshots" 
